inherit_gem:
  standard: config/base.yml

plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'references/**/*'
    # setup-ruby extracts gems to vendor/bundle
    - 'vendor/**/*'

Style/AccessModifierDeclarations:
  Enabled: true
  EnforcedStyle: inline

RSpec/DescribeClass:
  Exclude:
    - spec/draft7_spec.rb
    - spec/draft2019_09_spec.rb
    - spec/draft2020_12_spec.rb

RSpec/LeakyLocalVariable:
  Exclude:
    - spec/draft2019_09_spec.rb
    - spec/draft2020_12_spec.rb
