/* Generated by tool/native_generator.rb. Do not edit.
 * cleanup_regions: 571d5bd33a2a78ee11efb0a27085a20729f43e954b31d672eb5d7017dd634acf
 * generator: 99a863618a7c8b401c6a07cb70a24d8814853c50744e4405363076dbd32e31ee
 * generator_version: 2
 * intrinsics: c20792cc8177297736d166552376c3ead2358db583a906b5c6c79928e4942095
 * lowering_ir: ad5162510e75adc011a7dbb79b12c949ea026e27f5d8bb38ea505904b5d84c48
 * prism: 1.9.0
 * source: 850a865511c36a252080d9e500f8a327497e0cf3b2c4bd9a89b200b43762e1d4
 * translation_ir:bootstrap_type: 24af6fcccd03a392b1e88efb62f57ab85f251f87a3a450fda121e37851b3b40f
 * translation_ir:content: 2d9aa5b866c3cee9b5ad7e134b4bdab5bfb917151cd23db75509eb89ae81793c
 * translation_ir:dialect: a71feec56c34018da2b542067799f19f8c96c86bfb93f302367e648ef1d8d746
 * translation_ir:evaluation: 10a8f7be76e4e0e802377555647b08bbbd25537f59f436cabb2c95adffd2d266
 * translation_ir:format: 8433d736d139db16e574d5b5e72738a0afb47c3039087c921bca7e4c0b434897
 * translation_ir:result_construction: d3f08e70184703550e6daa546229ce11c10d1f51bc154400014067234b432b61
 * translation_ir:schema_compilation: ab3c79222380101854721917f9207371308b1b91d23a6be2ef0f7ccf0df17c2a
 * translation_ir:type_slice: de54029794f67dbb9fc2063d87510c03817da09df116628d6f07b7b450173ab7
 * translation_source:lib/schemurai/dialect.rb: 6a234e94399aef08c064f9f52dfa06b3d0b18c5c1713af3fa48d247bc22db8eb
 * translation_source:lib/schemurai/evaluator.rb: 3df32a45b6eefecf6b6f1cd863ce6c53fa010afd1b1a0a20526c5edbdf89997a
 * translation_source:lib/schemurai/formats.rb: 46031de70678ccadb08403f4df8a3fa9dea8bb0abf33cb8155fa11cddcdda21a
 * translation_source:lib/schemurai/schema_graph.rb: fd79b72d0714edbc6960fdee37fa0d53b3cf871f8737f274da0bd04f75bec268
 * translation_source:lib/schemurai/type_slice.rb: 0a86bb7338d145ba9b181201be554367e7f7d365c3c49f8eaf0f23a0999ddcda
 * translation_source:native/source/bootstrap.rb: 850a865511c36a252080d9e500f8a327497e0cf3b2c4bd9a89b200b43762e1d4
 * translation_units: 97dd0d1d610bb0564e67db4ccaa27f87eb18cd418ceed59fd1304bac772da2cf
 * type_slice_source: 0a86bb7338d145ba9b181201be554367e7f7d365c3c49f8eaf0f23a0999ddcda
 */
#include "ruby.h"
#include "ruby/thread.h"
#include <math.h>
#include <string.h>

#define SCHEMURAI_TYPE_NULL (1UL << 0)
#define SCHEMURAI_TYPE_BOOLEAN (1UL << 1)
#define SCHEMURAI_TYPE_OBJECT (1UL << 2)
#define SCHEMURAI_TYPE_ARRAY (1UL << 3)
#define SCHEMURAI_TYPE_NUMBER (1UL << 4)
#define SCHEMURAI_TYPE_INTEGER (1UL << 5)
#define SCHEMURAI_TYPE_STRING (1UL << 6)
#define SCHEMURAI_TYPE_ANY (1UL << 7)

VALUE
schemurai_generated_boolean_instance(VALUE self, VALUE instance)
{
    (void)self;
    return ((Qtrue == instance) || (Qfalse == instance)) ? Qtrue : Qfalse;
}

static unsigned long
schemurai_generated_type_name_mask(VALUE name)
{
    const char *bytes;
    long length;

    if (!RB_TYPE_P(name, T_STRING)) return 0;
    bytes = RSTRING_PTR(name);
    length = RSTRING_LEN(name);
    if (length == 4 && memcmp(bytes, "null", 4) == 0) return SCHEMURAI_TYPE_NULL;
    if (length == 7 && memcmp(bytes, "boolean", 7) == 0) return SCHEMURAI_TYPE_BOOLEAN;
    if (length == 6 && memcmp(bytes, "object", 6) == 0) return SCHEMURAI_TYPE_OBJECT;
    if (length == 5 && memcmp(bytes, "array", 5) == 0) return SCHEMURAI_TYPE_ARRAY;
    if (length == 6 && memcmp(bytes, "number", 6) == 0) return SCHEMURAI_TYPE_NUMBER;
    if (length == 7 && memcmp(bytes, "integer", 7) == 0) return SCHEMURAI_TYPE_INTEGER;
    if (length == 6 && memcmp(bytes, "string", 6) == 0) return SCHEMURAI_TYPE_STRING;
    return 0;
}

unsigned long
schemurai_generated_compile_type(VALUE schema)
{
    VALUE type;
    unsigned long mask = 0;
    long index;

    if (schema == Qtrue) return SCHEMURAI_TYPE_ANY;
    if (schema == Qfalse) return 0;
    Check_Type(schema, T_HASH);
    type = rb_hash_lookup2(schema, rb_str_new_cstr("type"), Qundef);
    if (type == Qundef) return SCHEMURAI_TYPE_ANY;
    if (!RB_TYPE_P(type, T_ARRAY)) return schemurai_generated_type_name_mask(type);
    for (index = 0; index < RARRAY_LEN(type); index++) {
        if ((((unsigned long)index) & 0x3ffUL) == 0) {
            rb_thread_schedule();
            rb_thread_check_ints();
        }
        mask |= schemurai_generated_type_name_mask(RARRAY_AREF(type, index));
    }
    return mask;
}

static int
schemurai_generated_number_p(VALUE value)
{
    VALUE complex = rb_const_get(rb_cObject, rb_intern("Complex"));
    return rb_obj_is_kind_of(value, rb_cNumeric) && !rb_obj_is_kind_of(value, complex);
}

static int
schemurai_generated_integer_p(VALUE value)
{
    VALUE converted;

    if (RB_INTEGER_TYPE_P(value)) return 1;
    if (RB_TYPE_P(value, T_FLOAT)) {
        double integral;
        return isfinite(RFLOAT_VALUE(value)) && modf(RFLOAT_VALUE(value), &integral) == 0.0;
    }
    if (!schemurai_generated_number_p(value)) return 0;

    /* cold_out_of_domain_compatibility: type_integer_out_of_domain_finite */
    if (!RTEST(rb_funcall(value, rb_intern("finite?"), 0))) return 0;
    /* cold_out_of_domain_compatibility: type_integer_out_of_domain_to_i */
    converted = rb_funcall(value, rb_intern("to_i"), 0);
    /* cold_out_of_domain_compatibility: type_integer_out_of_domain_equality */
    return RTEST(rb_equal(converted, value));
}

int
schemurai_generated_valid_type(unsigned long mask, VALUE value)
{
    if (mask & SCHEMURAI_TYPE_ANY) return 1;
    if (NIL_P(value)) return (mask & SCHEMURAI_TYPE_NULL) != 0;
    if (value == Qtrue || value == Qfalse) return (mask & SCHEMURAI_TYPE_BOOLEAN) != 0;
    if (RB_TYPE_P(value, T_HASH)) return (mask & SCHEMURAI_TYPE_OBJECT) != 0;
    if (RB_TYPE_P(value, T_ARRAY)) return (mask & SCHEMURAI_TYPE_ARRAY) != 0;
    if (RB_TYPE_P(value, T_STRING)) return (mask & SCHEMURAI_TYPE_STRING) != 0;
    if (RB_INTEGER_TYPE_P(value)) return (mask & (SCHEMURAI_TYPE_NUMBER | SCHEMURAI_TYPE_INTEGER)) != 0;
    if (RB_TYPE_P(value, T_FLOAT)) {
        if (mask & SCHEMURAI_TYPE_NUMBER) return 1;
        return (mask & SCHEMURAI_TYPE_INTEGER) != 0 && schemurai_generated_integer_p(value);
    }

    /* Subclasses and other Numeric implementations are outside the supported hot path. */
    if ((mask & SCHEMURAI_TYPE_OBJECT) && rb_obj_is_kind_of(value, rb_cHash)) return 1;
    if ((mask & SCHEMURAI_TYPE_ARRAY) && rb_obj_is_kind_of(value, rb_cArray)) return 1;
    if ((mask & SCHEMURAI_TYPE_STRING) && rb_obj_is_kind_of(value, rb_cString)) return 1;
    if ((mask & SCHEMURAI_TYPE_NUMBER) && schemurai_generated_number_p(value)) return 1;
    return (mask & SCHEMURAI_TYPE_INTEGER) != 0 && schemurai_generated_integer_p(value);
}
