/* Generated by tool/native_generator.rb. Do not edit.
 * generator: c92553f11e274f697be3829ec0b813a93819c3ab8212976eea900fca95b78bbf
 * generator_version: 1
 * intrinsics: b9af19bcc310fd0fdb88ebd6a03703b891e500b126e16fee3a7ee6132cba8dfc
 * lowering_ir: 56ef6b780fc832fdc95311808d4ca9329e2feddcf7378b5334730629fc42abb3
 * prism: 1.9.0
 * source: 850a865511c36a252080d9e500f8a327497e0cf3b2c4bd9a89b200b43762e1d4
 * translation_units: ccab5ba30f31c15924396208b3d6df5de634ca41410531a01ed5d0518c9bf963
 * type_slice_source: 0a86bb7338d145ba9b181201be554367e7f7d365c3c49f8eaf0f23a0999ddcda
 */
#include "ruby.h"
#include "ruby/thread.h"
#include <math.h>
#include <string.h>

#define SCHEMURAI_TYPE_NULL (1UL << 0)
#define SCHEMURAI_TYPE_BOOLEAN (1UL << 1)
#define SCHEMURAI_TYPE_OBJECT (1UL << 2)
#define SCHEMURAI_TYPE_ARRAY (1UL << 3)
#define SCHEMURAI_TYPE_NUMBER (1UL << 4)
#define SCHEMURAI_TYPE_INTEGER (1UL << 5)
#define SCHEMURAI_TYPE_STRING (1UL << 6)
#define SCHEMURAI_TYPE_ANY (1UL << 7)

VALUE
schemurai_generated_boolean_instance(VALUE self, VALUE instance)
{
    (void)self;
    return ((Qtrue == instance) || (Qfalse == instance)) ? Qtrue : Qfalse;
}

static unsigned long
schemurai_generated_type_name_mask(VALUE name)
{
    const char *bytes;
    long length;

    if (!RB_TYPE_P(name, T_STRING)) return 0;
    bytes = RSTRING_PTR(name);
    length = RSTRING_LEN(name);
    if (length == 4 && memcmp(bytes, "null", 4) == 0) return SCHEMURAI_TYPE_NULL;
    if (length == 7 && memcmp(bytes, "boolean", 7) == 0) return SCHEMURAI_TYPE_BOOLEAN;
    if (length == 6 && memcmp(bytes, "object", 6) == 0) return SCHEMURAI_TYPE_OBJECT;
    if (length == 5 && memcmp(bytes, "array", 5) == 0) return SCHEMURAI_TYPE_ARRAY;
    if (length == 6 && memcmp(bytes, "number", 6) == 0) return SCHEMURAI_TYPE_NUMBER;
    if (length == 7 && memcmp(bytes, "integer", 7) == 0) return SCHEMURAI_TYPE_INTEGER;
    if (length == 6 && memcmp(bytes, "string", 6) == 0) return SCHEMURAI_TYPE_STRING;
    return 0;
}

unsigned long
schemurai_generated_compile_type(VALUE schema)
{
    VALUE type;
    unsigned long mask = 0;
    long index;

    if (schema == Qtrue) return SCHEMURAI_TYPE_ANY;
    if (schema == Qfalse) return 0;
    Check_Type(schema, T_HASH);
    type = rb_hash_lookup2(schema, rb_str_new_cstr("type"), Qundef);
    if (type == Qundef) return SCHEMURAI_TYPE_ANY;
    if (!RB_TYPE_P(type, T_ARRAY)) return schemurai_generated_type_name_mask(type);
    for (index = 0; index < RARRAY_LEN(type); index++) {
        rb_thread_check_ints();
        mask |= schemurai_generated_type_name_mask(RARRAY_AREF(type, index));
    }
    return mask;
}

static int
schemurai_generated_number_p(VALUE value)
{
    VALUE complex = rb_const_get(rb_cObject, rb_intern("Complex"));
    return rb_obj_is_kind_of(value, rb_cNumeric) && !rb_obj_is_kind_of(value, complex);
}

static int
schemurai_generated_integer_p(VALUE value)
{
    VALUE converted;

    if (RB_INTEGER_TYPE_P(value)) return 1;
    if (RB_TYPE_P(value, T_FLOAT)) {
        double integral;
        return isfinite(RFLOAT_VALUE(value)) && modf(RFLOAT_VALUE(value), &integral) == 0.0;
    }
    if (!schemurai_generated_number_p(value)) return 0;

    /* cold_out_of_domain_compatibility: type_integer_out_of_domain_finite */
    if (!RTEST(rb_funcall(value, rb_intern("finite?"), 0))) return 0;
    /* cold_out_of_domain_compatibility: type_integer_out_of_domain_to_i */
    converted = rb_funcall(value, rb_intern("to_i"), 0);
    /* cold_out_of_domain_compatibility: type_integer_out_of_domain_equality */
    return RTEST(rb_equal(converted, value));
}

int
schemurai_generated_valid_type(unsigned long mask, VALUE value)
{
    if (mask & SCHEMURAI_TYPE_ANY) return 1;
    if (NIL_P(value)) return (mask & SCHEMURAI_TYPE_NULL) != 0;
    if (value == Qtrue || value == Qfalse) return (mask & SCHEMURAI_TYPE_BOOLEAN) != 0;
    if (RB_TYPE_P(value, T_HASH)) return (mask & SCHEMURAI_TYPE_OBJECT) != 0;
    if (RB_TYPE_P(value, T_ARRAY)) return (mask & SCHEMURAI_TYPE_ARRAY) != 0;
    if (RB_TYPE_P(value, T_STRING)) return (mask & SCHEMURAI_TYPE_STRING) != 0;
    if (RB_INTEGER_TYPE_P(value)) return (mask & (SCHEMURAI_TYPE_NUMBER | SCHEMURAI_TYPE_INTEGER)) != 0;
    if (RB_TYPE_P(value, T_FLOAT)) {
        if (mask & SCHEMURAI_TYPE_NUMBER) return 1;
        return (mask & SCHEMURAI_TYPE_INTEGER) != 0 && schemurai_generated_integer_p(value);
    }

    /* Subclasses and other Numeric implementations are outside the supported hot path. */
    if ((mask & SCHEMURAI_TYPE_OBJECT) && rb_obj_is_kind_of(value, rb_cHash)) return 1;
    if ((mask & SCHEMURAI_TYPE_ARRAY) && rb_obj_is_kind_of(value, rb_cArray)) return 1;
    if ((mask & SCHEMURAI_TYPE_STRING) && rb_obj_is_kind_of(value, rb_cString)) return 1;
    if ((mask & SCHEMURAI_TYPE_NUMBER) && schemurai_generated_number_p(value)) return 1;
    return (mask & SCHEMURAI_TYPE_INTEGER) != 0 && schemurai_generated_integer_p(value);
}
