/* Generated by tool/native_generator.rb. Do not edit.
 * generator: c0a98bd4705b10757d3d4ee3759976eddb742d7cb4c5a985eb0197f34915799b
 * generator_version: 1
 * intrinsics: b9af19bcc310fd0fdb88ebd6a03703b891e500b126e16fee3a7ee6132cba8dfc
 * lowering_ir: 56ef6b780fc832fdc95311808d4ca9329e2feddcf7378b5334730629fc42abb3
 * prism: 1.9.0
 * source: 850a865511c36a252080d9e500f8a327497e0cf3b2c4bd9a89b200b43762e1d4
 * translation_units: 9a9e23005f7086fe44fd20268155288f78bb05013160e0e734b8d53f63f4bb3d
 */
#include "ruby.h"

VALUE
schemurai_generated_boolean_instance(VALUE self, VALUE instance)
{
    (void)self;
    return ((Qtrue == instance) || (Qfalse == instance)) ? Qtrue : Qfalse;
}
