#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "optparse"
require_relative "../oracle/lib/runner"

backend = ENV.fetch("SCHEMURAI_BACKEND", "ruby")
OptionParser.new do |parser|
  parser.on("--backend BACKEND", %w[ruby native default]) { |value| backend = value }
end.parse!

runner = SchemuraiOracle::Runner.new(backend: backend)
$stdin.each_line do |line|
  next if line.strip.empty?

  puts JSON.generate(runner.run(JSON.parse(line)))
end
